import {
  PREVIEW_ACCEPTANCE_CRITERIA,
  type GamePreviewFrame,
  type PreviewAcceptanceCriterion,
  type PreviewIssueTag,
} from "./game-preview-history"
import type { PreviewAcceptancePlan } from "./game-preview-plan"
import { previewPlaytestScenarioSteps } from "./game-preview-run"

export const PREVIEW_REPORT_VERSION = 1

export type PreviewReportFrame = GamePreviewFrame & { imageDataURL: string }

export type PreviewReportInput = {
  projectName: string
  generatedAt: number
  frames: PreviewReportFrame[]
  plan: PreviewAcceptancePlan
  chinese: boolean
  criteriaLabels: ReadonlyMap<PreviewAcceptanceCriterion, string>
  issueLabels: ReadonlyMap<PreviewIssueTag, string>
  formatTime?: (value: number) => string
}

export function previewReportProjectName(directory: string) {
  return directory.replaceAll("\\", "/").split("/").filter(Boolean).at(-1) ?? "game-demo"
}

export function previewReportFilename(directory: string, generatedAt: number) {
  const project = previewReportProjectName(directory)
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60)
  return `km-agent-${project || "game-demo"}-playtest-${new Date(generatedAt).toISOString().slice(0, 10)}.html`
}

export function previewReportStats(frames: Pick<GamePreviewFrame, "checks" | "scenario" | "run">[]) {
  const checks = frames.flatMap((frame) => Object.values(frame.checks))
  return {
    iterations: frames.length,
    passed: checks.filter((state) => state === "pass").length,
    failed: checks.filter((state) => state === "fail").length,
    untested: frames.length * PREVIEW_ACCEPTANCE_CRITERIA.length - checks.length,
    scenarios: new Set(frames.flatMap((frame) => frame.scenario?.id ?? [])).size,
    runsPassed: frames.filter((frame) => frame.run?.expected === "pass").length,
    runsFailed: frames.filter((frame) => frame.run?.expected === "fail").length,
  }
}

export function previewReportHTML(input: PreviewReportInput) {
  const copy = input.chinese
    ? {
        lang: "zh-CN",
        title: "试玩评审报告",
        generated: "生成时间",
        iterations: "试玩迭代",
        passed: "通过项",
        failed: "需修复",
        untested: "未测试",
        scenarios: "覆盖场景",
        runsPassed: "场景通过",
        runsFailed: "场景未通过",
        plan: "项目验收计划",
        noPlan: "尚未配置项目验收标准。",
        scenario: "试玩场景",
        steps: "测试步骤",
        expected: "预期结果",
        run: "执行结果",
        runNote: "策划备注",
        history: "迭代记录",
        frame: "迭代",
        source: "试玩地址",
        checks: "验收结果",
        tags: "问题标签",
        notes: "策划批注",
        noNotes: "无批注",
        pass: "通过",
        fail: "需修复",
        pending: "未测试",
        footer: "由 KM Agent 生成 · 单文件离线报告",
      }
    : {
        lang: "en",
        title: "Playtest review report",
        generated: "Generated",
        iterations: "Iterations",
        passed: "Passed checks",
        failed: "Needs fixing",
        untested: "Untested",
        scenarios: "Scenarios covered",
        runsPassed: "Scenario passes",
        runsFailed: "Scenario failures",
        plan: "Project acceptance plan",
        noPlan: "No project acceptance criteria configured.",
        scenario: "Playtest scenario",
        steps: "Test steps",
        expected: "Expected result",
        run: "Run result",
        runNote: "Designer note",
        history: "Iteration history",
        frame: "Iteration",
        source: "Preview URL",
        checks: "Acceptance checks",
        tags: "Issue tags",
        notes: "Designer notes",
        noNotes: "No notes",
        pass: "Pass",
        fail: "Fix",
        pending: "Untested",
        footer: "Generated by KM Agent · Self-contained offline report",
      }
  const formatTime = input.formatTime ?? ((value: number) => new Date(value).toLocaleString(copy.lang))
  const frames = [...input.frames].sort((a, b) => a.createdAt - b.createdAt)
  const stats = previewReportStats(frames)
  const plan = PREVIEW_ACCEPTANCE_CRITERIA.flatMap((criterion) => {
    const requirement = input.plan.criteria[criterion]
    if (!requirement) return []
    return `<li><strong>${escapeHTML(input.criteriaLabels.get(criterion) ?? criterion)}</strong><span>${textHTML(requirement)}</span></li>`
  }).join("")
  const timeline = frames
    .map((frame, index) => {
      const checks = PREVIEW_ACCEPTANCE_CRITERIA.map((criterion) => {
        const state = frame.checks[criterion]
        const label = state === "pass" ? copy.pass : state === "fail" ? copy.fail : copy.pending
        return `<div class="check ${state ?? "pending"}"><span>${escapeHTML(input.criteriaLabels.get(criterion) ?? criterion)}</span><strong>${label}</strong></div>`
      }).join("")
      const tags = frame.tags
        .map((tag) => `<span class="tag">${escapeHTML(input.issueLabels.get(tag) ?? tag)}</span>`)
        .join("")
      const run =
        frame.scenario && frame.run
          ? `<div><strong>${copy.run}</strong><ol class="run-list">${previewPlaytestScenarioSteps(frame.scenario)
              .map((step, stepIndex) => {
                const state = frame.run?.checks[stepIndex]
                const label = state === "pass" ? copy.pass : state === "fail" ? copy.fail : copy.pending
                return `<li class="${state || "pending"}"><span>${textHTML(step)}</span><b>${label}</b></li>`
              })
              .join("")}<li class="${frame.run.expected || "pending"}"><span>${copy.expected}</span><b>${
              frame.run.expected === "pass" ? copy.pass : frame.run.expected === "fail" ? copy.fail : copy.pending
            }</b></li></ol>${
              frame.run.note
                ? `<p class="run-note"><strong>${copy.runNote}</strong><span>${textHTML(frame.run.note)}</span></p>`
                : ""
            }</div>`
          : ""
      const scenario = frame.scenario
        ? `<section class="scenario"><h3>${copy.scenario}: ${escapeHTML(frame.scenario.name)}</h3>${
            frame.scenario.steps
              ? `<div><strong>${copy.steps}</strong><p>${textHTML(frame.scenario.steps)}</p></div>`
              : ""
          }${
            frame.scenario.expected
              ? `<div><strong>${copy.expected}</strong><p>${textHTML(frame.scenario.expected)}</p></div>`
              : ""
          }${run}</section>`
        : ""
      const image = frame.imageDataURL.startsWith("data:image/png;base64,") ? frame.imageDataURL : ""
      const source = safeHTTPURL(frame.url)
      return `<article class="frame">
        <div class="frame-heading"><div><span class="eyebrow">${copy.frame} ${index + 1}</span><h2>${escapeHTML(formatTime(frame.createdAt))}</h2></div>${source ? `<a href="${escapeHTML(source)}">${copy.source}</a>` : ""}</div>
        ${image ? `<img class="screenshot" src="${escapeHTML(image)}" alt="${copy.frame} ${index + 1}">` : ""}
        ${scenario}
        <section><h3>${copy.checks}</h3><div class="checks">${checks}</div></section>
        ${tags ? `<section><h3>${copy.tags}</h3><div class="tags">${tags}</div></section>` : ""}
        <section><h3>${copy.notes}</h3><p class="notes ${frame.note ? "" : "muted"}">${frame.note ? textHTML(frame.note) : copy.noNotes}</p></section>
      </article>`
    })
    .join("")
  return `<!doctype html>
<html lang="${copy.lang}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHTML(input.projectName)} · ${copy.title}</title>
  <style>
    :root{color-scheme:light;--ink:#172018;--muted:#647066;--line:#dfe6df;--paper:#f4f7f4;--card:#fff;--accent:#2f6f46;--pass:#25643b;--pass-bg:#e6f4e9;--fail:#a2362c;--fail-bg:#fbe9e7;--pending:#6a706b;--pending-bg:#eef1ee}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:14px/1.55 ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.page{width:min(1040px,calc(100% - 32px));margin:0 auto;padding:48px 0 64px}.hero{padding:36px;border:1px solid var(--line);border-radius:22px;background:linear-gradient(145deg,#fff,#edf5ef);box-shadow:0 18px 45px rgba(32,55,37,.08)}.brand,.eyebrow{color:var(--accent);font-size:11px;font-weight:750;letter-spacing:.12em;text-transform:uppercase}.hero h1{margin:8px 0 4px;font-size:34px;line-height:1.15}.meta{color:var(--muted)}.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(110px,1fr));gap:10px;margin-top:28px}.stat{padding:14px;border:1px solid var(--line);border-radius:12px;background:rgba(255,255,255,.78)}.stat strong{display:block;font-size:22px}.stat span{color:var(--muted);font-size:11px}.section{margin-top:28px;padding:26px;border:1px solid var(--line);border-radius:18px;background:var(--card)}.section>h2,.history-title{margin:0 0 16px;font-size:18px}.plan{display:grid;gap:10px;margin:0;padding:0;list-style:none}.plan li{display:grid;grid-template-columns:minmax(130px,1fr) 3fr;gap:16px;padding:11px 0;border-bottom:1px solid var(--line)}.plan li:last-child{border:0}.plan span,.muted{color:var(--muted)}.history-title{margin-top:34px}.frame{margin-top:18px;padding:24px;border:1px solid var(--line);border-radius:18px;background:var(--card);break-inside:avoid}.frame-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.frame-heading h2{margin:3px 0 0;font-size:17px}.frame-heading a{color:var(--accent);font-size:12px}.screenshot{display:block;width:100%;max-height:620px;object-fit:contain;margin:18px 0;border-radius:12px;background:#111}.frame section{margin-top:18px}.frame h3{margin:0 0 8px;font-size:13px}.scenario{padding:16px;border-radius:12px;background:#f0f5f1}.scenario>div{display:grid;grid-template-columns:120px 1fr;gap:12px;margin-top:8px}.scenario p,.notes{margin:0}.run-list{display:grid;gap:5px;margin:0;padding:0;list-style:none}.run-list li{display:flex;justify-content:space-between;gap:12px;padding:5px 7px;border-radius:7px}.run-list li.pass{color:var(--pass);background:var(--pass-bg)}.run-list li.fail{color:var(--fail);background:var(--fail-bg)}.run-list li.pending{color:var(--pending);background:var(--pending-bg)}.run-note{display:flex;gap:8px;margin-top:8px!important}.checks{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.check{display:flex;justify-content:space-between;gap:8px;padding:9px 10px;border-radius:9px}.check.pass{color:var(--pass);background:var(--pass-bg)}.check.fail{color:var(--fail);background:var(--fail-bg)}.check.pending{color:var(--pending);background:var(--pending-bg)}.tags{display:flex;flex-wrap:wrap;gap:6px}.tag{padding:4px 8px;border-radius:999px;background:#eef1ee;color:#4f5a51;font-size:12px}.footer{margin-top:28px;color:var(--muted);font-size:11px;text-align:center}@media(max-width:720px){.page{width:min(100% - 20px,1040px);padding-top:16px}.hero{padding:24px}.stats{grid-template-columns:repeat(2,1fr)}.checks{grid-template-columns:1fr}.plan li,.scenario>div{grid-template-columns:1fr;gap:4px}.frame{padding:16px}}@media print{body{background:#fff}.page{width:100%;padding:0}.hero,.section,.frame{box-shadow:none}.frame{break-inside:avoid}.frame-heading a{display:none}}
  </style>
</head>
<body><main class="page">
  <header class="hero"><div class="brand">KM Agent</div><h1>${escapeHTML(input.projectName)} · ${copy.title}</h1><div class="meta">${copy.generated}: ${escapeHTML(formatTime(input.generatedAt))}</div><div class="stats">
    <div class="stat"><strong>${stats.iterations}</strong><span>${copy.iterations}</span></div>
    <div class="stat"><strong>${stats.passed}</strong><span>${copy.passed}</span></div>
    <div class="stat"><strong>${stats.failed}</strong><span>${copy.failed}</span></div>
    <div class="stat"><strong>${stats.untested}</strong><span>${copy.untested}</span></div>
    <div class="stat"><strong>${stats.scenarios}</strong><span>${copy.scenarios}</span></div>
    <div class="stat"><strong>${stats.runsPassed}</strong><span>${copy.runsPassed}</span></div>
    <div class="stat"><strong>${stats.runsFailed}</strong><span>${copy.runsFailed}</span></div>
  </div></header>
  <section class="section"><h2>${copy.plan}</h2>${plan ? `<ul class="plan">${plan}</ul>` : `<p class="muted">${copy.noPlan}</p>`}</section>
  <h2 class="history-title">${copy.history}</h2>${timeline}
  <footer class="footer">${copy.footer} · v${PREVIEW_REPORT_VERSION}</footer>
</main></body>
</html>`
}

export function previewReportFrame(frame: GamePreviewFrame) {
  return new Promise<PreviewReportFrame>((resolve, reject) => {
    const reader = new FileReader()
    reader.addEventListener(
      "load",
      () => {
        if (typeof reader.result !== "string") {
          reject(new Error("Could not encode playtest frame"))
          return
        }
        resolve({ ...frame, imageDataURL: reader.result })
      },
      { once: true },
    )
    reader.addEventListener("error", () => reject(reader.error ?? new Error("Could not read playtest frame")), {
      once: true,
    })
    reader.readAsDataURL(frame.image.slice(0, frame.image.size, "image/png"))
  })
}

function escapeHTML(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;")
}

function textHTML(value: string) {
  return escapeHTML(value).replaceAll("\n", "<br>")
}

function safeHTTPURL(value: string) {
  if (!URL.canParse(value)) return ""
  const url = new URL(value)
  if (url.protocol !== "http:" && url.protocol !== "https:") return ""
  return url.href
}
